site_name: OpenAI .NET Documentation
nav:
- Overview: index.md
# START EXAMPLES #
- Examples:
  - Chat:
    - SimpleChat: samples/Chat.SimpleChat.md
    - SimpleChatStreaming: samples/Chat.SimpleChatStreaming.md
    - ChatWithVision: samples/Chat.ChatWithVision.md
    - FunctionCalling: samples/Chat.FunctionCalling.md
    - FunctionCallingService: samples/Chat.FunctionCallingService.md
  - Assistants:
    - AssistantsWithVision: samples/Assistants.AssistantsWithVision.md
    - ListFiles: samples/Assistants.ListFiles.md
    - ListAssistantsWithPagination: samples/Assistants.ListAssistantsWithPagination.md
    - RetrievalAugmentedGeneration: samples/Assistants.RetrievalAugmentedGeneration.md
  - Images:
    - SimpleImageEdit: samples/Images.SimpleImageEdit.md
    - SimpleImageVariation: samples/Images.SimpleImageVariation.md
    - SimpleImageGeneration: samples/Images.SimpleImageGeneration.md
  - Embeddings:
    - MultipleEmbeddings: samples/Embeddings.MultipleEmbeddings.md
    - SimpleEmbedding: samples/Embeddings.SimpleEmbedding.md
    - EmbeddingWithOptions: samples/Embeddings.EmbeddingWithOptions.md
  - Audio:
    - SimpleTranscription: samples/Audio.SimpleTranscription.md
    - SimpleTranslation: samples/Audio.SimpleTranslation.md
    - VerboseTranscription: samples/Audio.VerboseTranscription.md
    - SimpleTextToSpeech: samples/Audio.SimpleTextToSpeech.md
  - Combination:
    - CuriousCreatureCreator: samples/Combination.CuriousCreatureCreator.md
    - AlpacaArtAssessor: samples/Combination.AlpacaArtAssessor.md
# END EXAMPLES #

#  - Quick Start: QuickStart.md
#  - Architecture: Architecture.md
#  - FAQ: FAQ.md
#  - Contributing Guide: ContributingGuide.md
#  - Tutorials:
#      - Configure the native library loading: Tutorials/NativeLibraryConfig.md
#      - Use executors: Tutorials/Executors.md
#      - Use ChatSession: Tutorials/ChatSession.md
#      - Understand LLamaContext: Tutorials/UnderstandLLamaContext.md
#      - Get embeddings: Tutorials/GetEmbeddings.md
#      - Quantize the model: Tutorials/Quantization.md
#
#  - Advanced Tutorials:
#      - Customize the native library loading: AdvancedTutorials/CustomizeNativeLibraryLoading.md
#
#  - Integrations:
#      - semantic-kernel integration: Integrations/semantic-kernel.md
#      - kernel-memory integration: Integrations/kernel-memory.md
#      - BotSharp integration: Integrations/BotSharp.md
#      - Langchain integration: Integrations/Langchain.md
#
#  - Examples:
#      - Bacthed executor - multi-output to one input: Examples/BatchedExecutorFork.md
#      - Batched executor - basic guidance: Examples/BatchedExecutorGuidance.md
#      - Batched executor - rewinding to an earlier state: Examples/BatchedExecutorRewind.md
        
theme:
  name: material
  static_templates:
    - 404.html
  language: 'en'
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  include_search_page: false
  search_index_only: true
  favicon: 'media/icon128.png'
  icon:
    logo: 'material/file-document'
  features:
    - content.action.edit
    - navigation.instant
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'

extra:
  version:
    provider: mike

extra_css:
  - 'css/extra.css?v=14'

markdown_extensions:
  - admonition
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: ""
      slugify: !!python/name:pymdownx.slugs.uslugify
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true